#!/bin/sh
# check.sh — integrity check for this repository's vendored constellation standards.
#
# Generated by the constellation's operations/scripts/sync-standards.sh and vendored with the
# standards; do not edit (SHA256SUMS covers this file too). Standalone: needs only POSIX sh and
# sha256sum or shasum. It verifies that
#   1. every file in this directory matches SHA256SUMS and no unlisted file was added;
#   2. the repository-root AGENTS.md carries the constellation-standards managed block.
# Run it from anywhere (e.g. in CI):   sh docs/standards/check.sh
# Exit status: 0 = intact, 1 = verification failed, 2 = cannot run.

set -u

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 2
cd "$here" || exit 2

begin_marker='<!-- constellation-standards:begin -->'
end_marker='<!-- constellation-standards:end -->'
status=0

fail() {
  printf 'standards check: FAIL: %s\n' "$1" >&2
  status=1
}

if command -v sha256sum >/dev/null 2>&1; then
  sumcmd='sha256sum -c'
elif command -v shasum >/dev/null 2>&1; then
  sumcmd='shasum -a 256 -c'
else
  printf 'standards check: cannot run: neither sha256sum nor shasum is installed\n' >&2
  exit 2
fi

if [ ! -f SHA256SUMS ]; then
  fail "docs/standards/SHA256SUMS is missing"
else
  if ! out=$($sumcmd SHA256SUMS 2>&1); then
    fail "vendored files do not match docs/standards/SHA256SUMS:"
    printf '%s\n' "$out" | grep -v ': OK$' | sed 's/^/    /' >&2
  fi
  for f in * .[!.]*; do
    [ -e "$f" ] || continue
    [ "$f" = SHA256SUMS ] && continue
    if ! awk -v f="$f" '{ sub(/^[0-9a-fA-F]+ [ *]/, ""); if ($0 == f) found = 1 }
                        END { exit !found }' SHA256SUMS; then
      fail "docs/standards/$f is not listed in SHA256SUMS (files were added by hand)"
    fi
  done
fi

agents=../../AGENTS.md
if [ ! -f "$agents" ]; then
  fail "AGENTS.md is missing at the repository root (it must carry the constellation-standards block)"
elif ! awk -v b="$begin_marker" -v e="$end_marker" '
       { l = $0; sub(/\r$/, "", l); sub(/^[ \t]+/, "", l); sub(/[ \t]+$/, "", l)
         if (l == b && !bl) bl = NR
         if (l == e && bl && !el) el = NR }
       END { exit !(bl && el) }' "$agents"; then
  fail "AGENTS.md is missing the managed block between '$begin_marker' and '$end_marker'"
fi

if [ "$status" -ne 0 ]; then
  {
    printf '%s\n' "vendored standards were edited — re-sync with operations/scripts/sync-standards.sh; record deviations in docs/design/<feature>/4_decisions.md"
    printf '%s\n' "(re-sync from the constellation umbrella: operations/scripts/sync-standards.sh <this-repo>; see docs/standards/README.md)"
  } >&2
  exit 1
fi
printf 'standards check: OK (docs/standards intact, AGENTS.md block present)\n'
exit 0
